spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teste_db
    username: root
    password: teste1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
